### ISSUE TITLE
[CHORE] - identifier 변경 후 등록

### ISSUE THREAD

**Issue by dlwns33** [zaranaramorimori/HACKER-iOS#10]
# 👀 이슈 (Issue)

이준 계정(개발자 계정)에 Identifier을 등록해야하는데 중복되어서 등록되지 않는 이슈 때문에
- 팀계정 변경
- identifier 변경 
- 개발자 계정에 등록 진행하게씁니다!

# 👨🏻‍🦲 TO-DO

- [x] 팀계정 변경 
- [x] identifier 변경

**Comment by Kim-jisoo11** [comment]
달려달려~!~!👩🏻‍🦲
