### ISSUE TITLE
[FIX] - 소셜 로그인 200, 201 분기처리

### ISSUE THREAD

**Issue by dlwns33** [zaranaramorimori/HACKER-iOS#68]
# 👀 이슈 (Issue)

소셜 로그인 200, 201 분기처리와 싸워서 이기자

# 👨🏻‍🦲 TO-DO

- [ ] 소셜 로그인 200, 201 분기처리

**Comment by dannaward** [comment]
89번 브랜치에 머지해서 반영 완료 ~!
