### ISSUE TITLE
[FIX] - RankingCVC 상세조회 연결

### ISSUE THREAD

**Issue by Kim-jisoo11** [zaranaramorimori/HACKER-iOS#73]
# 👀 이슈 (Issue)

RankingCVC 상세조회 연결할 예정

# 👨🏻‍🦲 TO-DO

- [ ] RankingCVC 상세조회 연결

**Comment by dannaward** [comment]
이게 내가 하는 그거지? 이슈 번호 갖다 쓸게~!

**Comment by Kim-jisoo11** [comment]
@dannaward 엉엉.. 이슈번호 가져다 쓰는거 확인..언냐 진짜 너무 멋져..🥲👍🏻
